"""Build the synthetic transit example: a tree, a matching screenshot, and the
same screen at 200% font scale.

Everything here is synthetic and generated by this script, so the example is
reproducible and makes no claim about any real app. Text is drawn as simple
vertical strokes, which is enough for the contrast check to measure colors.

    python examples/build_examples.py
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent / "src"))
from a11yjourney.imaging import encode  # noqa: E402

W, H, DENSITY = 1080, 2160, 3.0
WHITE = (255, 255, 255)
INK = (0x21, 0x21, 0x21)
BLUE = (0x0B, 0x57, 0xD0)
LIGHT = (0xA8, 0xA8, 0xA8)
FAINT = (0xD6, 0xD6, 0xD6)
FIELD = (0xF1, 0xF3, 0xF4)

# name: (class, rid, text, desc, clickable, normal bounds, bounds at 200%, fill, ink)
ELEMENTS = [
    ("TextView", "title", "Trip planner", "", False,
     (48, 60, 700, 150), (48, 60, 1000, 240), None, INK),
    ("TextView", "alert", "Service alert: Route 7 detour", "", False,
     (48, 170, 1032, 230), None, None, INK),
    ("EditText", "from", "", "Starting point", True,
     (48, 260, 1032, 400), (48, 260, 1032, 460), FIELD, INK),
    ("EditText", "to", "", "", True,
     (48, 420, 900, 560), (48, 480, 900, 680), FIELD, INK),
    ("ImageButton", "swap", "", "Swap start and destination", True,
     (930, 460, 990, 520), (930, 550, 990, 610), None, INK),
    ("TextView", "leave", "Leave now", "", False,
     (48, 590, 500, 650), (48, 700, 700, 820), None, LIGHT),
    ("Button", "plan", "Plan trip", "", True,
     (48, 690, 1032, 834), (48, 850, 1032, 994), BLUE, WHITE),
    ("TextView", "route", "Route 7 to Downtown, 12 min", "", False,
     (48, 900, 1032, 960), (48, 1020, 1032, 1140), None, INK),
    ("TextView", "eta", "Arrives 5:42 PM", "", False,
     (48, 970, 600, 1030), (48, 1100, 900, 1220), None, INK),
    ("ImageButton", "options", "", "Accessible trip options", True,
     (900, 1060, 1032, 1192), (900, 1250, 1032, 1382), None, FAINT),
]


def node(cls, rid, text, desc, clickable, bounds):
    x1, y1, x2, y2 = bounds
    return (f'    <node class="android.widget.{cls}" resource-id="org.example.transit:id/{rid}" '
            f'text="{text}" content-desc="{desc}" clickable="{str(clickable).lower()}" '
            f'focusable="true" enabled="true" bounds="[{x1},{y1}][{x2},{y2}]"/>')


def tree(large: bool) -> str:
    rows = []
    for cls, rid, text, desc, clickable, normal, big, _fill, _ink in ELEMENTS:
        bounds = big if large else normal
        if bounds is not None:
            rows.append(node(cls, rid, text, desc, clickable, bounds))
    body = "\n".join(rows)
    return (f'<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<!-- Synthetic example generated by build_examples.py -->\n'
            f'<hierarchy rotation="0" density="{DENSITY:g}">\n'
            f'  <node class="android.widget.FrameLayout" bounds="[0,0][{W},{H}]">\n'
            f'{body}\n  </node>\n</hierarchy>\n')


def screenshot() -> bytes:
    px = [WHITE] * (W * H)
    for _cls, _rid, text, desc, _c, (x1, y1, x2, y2), _big, fill, ink in ELEMENTS:
        if fill:
            for y in range(y1, y2):
                px[y * W + x1: y * W + x2] = [fill] * (x2 - x1)
        label = text or (desc if _cls == "ImageButton" else "")
        if not label:
            continue
        # glyph strokes, inset from the element's bounds
        gx1, gy1 = x1 + 24, y1 + (y2 - y1) // 4
        gx2 = min(x2 - 24, gx1 + 26 * len(label)) if text else x2 - 24
        gy2 = y2 - (y2 - y1) // 4
        for y in range(gy1, gy2):
            for x in range(gx1, gx2):
                phase = (x - gx1) % 13
                if phase < 4:
                    px[y * W + x] = ink
                elif phase == 4:
                    bg = px[y * W + x]
                    px[y * W + x] = tuple((a + b) // 2 for a, b in zip(ink, bg))
    return encode(W, H, px)


if __name__ == "__main__":
    out = pathlib.Path(__file__).parent / "transit"
    out.mkdir(exist_ok=True)
    (out / "trip.xml").write_text(tree(large=False))
    (out / "trip.large.xml").write_text(tree(large=True))
    (out / "trip.png").write_bytes(screenshot())
    print("wrote", ", ".join(sorted(p.name for p in out.iterdir())))
